### ISSUE TITLE
Feature request: floating layer

### ISSUE THREAD

**Issue by tbdcit** [mogenson/PaperWM.spoon#24]
Thanks for the excellent window manager! 

Are there any plans to add a floating layer in a similar way to PaperWM for Gnome?

**Comment by mogenson** [comment]
Hello, I don't have any immediate plans to add a floating layer feature. However, I'd be happy to review a PR!

There is a option in your hammerspoon config to modify the window filter to ignore matching windows or applications. From the README:

> Overwrite PaperWM.window_filter to ignore specific applications. For example:
> ```
> PaperWM.window_filter = PaperWM.window_filter:setAppFilter("Finder", false)
> PaperWM:start() -- restart for new window filter to take effect
> ```

Maybe you could make a keybinding to dynamically add or remove a specific window from the window filter.
