### ISSUE TITLE
Expose user-accessible action references to enable creating redundant keybindings

### ISSUE THREAD

**Issue by ambirdsall** [mogenson/PaperWM.spoon#26]
Most of the time, I like to use vim-style home row directions for navigating the windows; but I also appreciate how the GNOME PaperWM lets me have this _and_ sideswipe gestures (I'm not aware of a simple hammerspoon API for scripting gestures, but I could easily see one getting added in the future) _and_ use the arrow keys (for example, when carrying my laptop around and using the keyboard one-handed).

Right now, I'm able to create these duplicate bindings manually, by using code like
```lua
-- in fact, I use fennel for my config, so there's a small chance this code snippet is incorrect
hs.hotkey.bind({{"cmd", "alt"}, "left"}, function () PaperWM:focusWindow(-1) end)
```
But this approach is undocumented, hard to read, and it generally feels brittle and hacky. Ideally, this would be unnecessary (see https://github.com/Hammerspoon/hammerspoon/issues/3569), but for the time being, it would be very nice if the definitions of preconfigured user actions (i.e. the function bindings for partially-applied methods created inside `PaperWM:bindHotkeys`) were moved to somewhere user accessible. I was thinking a property of the module table akin to `PaperWM.default_hotkeys`; does this sound reasonable?

I'm happy to create a PR for this—in fact, I intend to write the patch regardless, for my own benefit, but it would be nice to not have to rebase upstream changes and deal with potential conflicts in perpetuity.

**Comment by mogenson** [comment]
I'd be happy to accept a PR. When experimenting with BetterTouchTool to map swipe gestures to keyboard shortcuts I also noticed the limitation around binding multiple keyboard shortcuts with bindHotkeys.

You could make public wrapper functions for focusWindow, swapWindows, etc. or you could expose the Direction enum. Either seems fine with me.
