### ISSUE TITLE
Automatically move windows when 1 window is minimised

### ISSUE THREAD

**Issue by AlDrag** [mogenson/PaperWM.spoon#36]
## How to reproduce

1. Open at least 3 windows.
2. Move to the far left window.
3. Minimise the 2nd window (directly to the right of the currently focused far left window).
4. Observe that the 3rd window doesn't automatically move to be directly next to the first window unless you navigate.

Also seems you can't navigate between tiles with the keyboard when you un-minimise a window, since it gets focused any for some reason ignores any PaperWM.spoon key bindings.

**Comment by mogenson** [comment]
This seems to happen when the minimized window is not the focused window. In that case the focused window does not change at all and we don't check if windows need to be retiled.

I'll work on a fix.

**Comment by mogenson** [comment]
@AlDrag See if the problem still exists with the addition of #38. If so, feel free to re-open this issue.
