### ISSUE TITLE
Feature request: Pull all windows back on screen when turning it off

### ISSUE THREAD

**Issue by Supreeeme** [mogenson/PaperWM.spoon#50]
Right now if you turn it off, it stops messing with the windows, but it leaves open windows on the edges of the screen, so you have to pull them back on screen. This is unfortunate, because sometimes I want the scrolling behavior, but sometimes I want the standard behavior, and having to pull all the windows back is annoying. It would be nice to just pull all the windows back into the center of the screen.

**Comment by mogenson** [comment]
Try out #51 and see if it works for you.

**Comment by Supreeeme** [comment]
It works great! Thanks for the quick response.
